project:
  type: website
  output-dir: ../docs

website:
  title: "ambiorix-examples"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ambiorix-web/ambiorix-examples
      - icon: twitter
        href: https://x.com/ambiorixweb
format:
  html:
    theme: lux
    css: styles.css
    toc: true
